//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SDKDEMO_EN.rc
//
#define IDR_MANIFEST                    1
#define IDD_SDKDEMO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN_DIALOG                129
#define IDD_LIVE_DIALOG                 130
#define IDR_MENU_LIVE                   131
#define IDR_MENU_POPUP                  131
#define IDD_SEARCH_DIALOG               132
#define IDB_BITMAP_PTZ1                 133
#define IDB_BITMAP_PTZ2                 134
#define IDD_BACKUP_DIALOG               134
#define IDB_BITMAP_PTZ3                 135
#define IDD_PLAYBACK_DIALOG             135
#define IDB_BITMAP_PTZ4                 136
#define IDD_TOOL_DIALOG                 136
#define IDB_BITMAP_PTZ5                 137
#define IDD_CONFIG_DIALOG               137
#define IDB_BITMAP_PTZ6                 138
#define IDD_CRUISE_DIALOG               138
#define IDB_BITMAP_PTZ7                 139
#define IDB_BITMAP_PTZ8                 140
#define IDD_FORMAT_DIALOG               140
#define IDB_BITMAP_PTZ9                 141
#define IDD_MSG_DIALOG                  141
#define IDD_DEVICE_DIALOG               142
#define IDD_CONNECT_MODE                143
#define IDD_FACE_MATCH_DIALOG           146
#define IDD_SMART_DIALOG                147
#define IDD_TEMPERATURE_DIALOG          148
#define IDD_FACE_MATCH_ALARM_DISPLAY_DIALOG 149
#define IDD_OTHERS_DIALOG               150
#define IDC_IPADDRESS                   1000
#define IDC_EDIT_USERNAME               1001
#define IDC_MAIN_TAB                    1002
#define IDC_EDIT_PASSWORD               1002
#define IDC_EDIT_PORT                   1003
#define IDC_LIVE_AREA                   1004
#define IDC_EDIT_PORT2                  1004
#define IDC_EDIT_DEVICE_SN              1004
#define IDC_COMBO_CHANNEL               1005
#define IDC_SLIDER_BRIGHTNESS           1007
#define IDC_SLIDER_SATURATION           1008
#define IDC_SLIDER_HUE                  1009
#define IDC_SLIDER_CONTRAST             1010
#define IDC_BUTTON_COLOR_DEFAULT        1011
#define IDC_BUTTON_COLOR_SAVE           1012
#define IDC_SLIDER_VOLUME               1013
#define IDC_BUTTON_LIVE                 1014
#define IDC_BUTTON_BACKUP               1015
#define IDC_LIST_RESULT                 1016
#define IDC_BUTTON_PTZ1                 1017
#define IDC_BUTTON_PTZ2                 1018
#define IDC_BUTTON_PTZ3                 1019
#define IDC_BUTTON_PTZ4                 1020
#define IDC_BUTTON_PTZ5                 1021
#define IDC_BUTTON_PTZ6                 1022
#define IDC_BUTTON_PTZ7                 1023
#define IDC_BUTTON_PTZ8                 1024
#define IDC_BUTTON_PTZ9                 1025
#define IDC_COMBO_CHNN                  1026
#define IDC_DATETIMEPICKER_DATE         1027
#define IDC_TAB_SEARCHTYPE              1028
#define IDC_BUTTON_LOCK                 1029
#define IDC_BUTTON_UNLOCK               1030
#define IDC_BUTTON_DELETE               1031
#define IDC_RADIO_EVENTTYPE_MOTION      1032
#define IDC_RADIO_EVENTTYPE_SENSOR      1033
#define IDC_RADIO_EVENTTYPE_ALL         1034
#define IDC_BUTTON_SEARCH               1035
#define IDC_BUTTON_HEAD                 1036
#define IDC_BUTTON_set_temperature      1036
#define IDC_BUTTON_TAIL                 1037
#define IDC_BUTTON1                     1037
#define IDC_BUTTON_BROWSER              1037
#define IDC_BUTTON_PLAYBACK             1037
#define IDC_BUTTON_SEARCHLOG            1037
#define IDC_BUTTON_BROWSE_EXPORT_PATH   1037
#define IDC_BUTTON_NEAR                 1037
#define IDC_BUTTON_ADD                  1037
#define IDC_PRODUCT_SUB_ID              1037
#define IDC_GET_GROUPS_BUTTON           1037
#define IDC_BTN_VIEW_IMG                1037
#define IDC_BUTTON_set_mask             1037
#define IDC_BUTTON_WATERMASKSETTING     1037
#define IDC_BUTTON_LAST                 1038
#define IDC_GROUP_BACKUP                1038
#define IDC_BUTTON_STOP                 1038
#define IDC_BUTTON_FAR                  1038
#define IDC_BUTTON_MSG_CLEAR            1038
#define IDC_ADD_GROUPS_BUTTON           1038
#define IDC_BUTTON_set_thermal          1038
#define IDC_BUTTON_NEXT                 1039
#define IDC_STATIC_BACKUP               1039
#define IDC_BUTTON_REW                  1039
#define IDC_BUTTON_IN                   1039
#define IDC_BUTTON_DELETEALL            1039
#define IDC_EDIT_GROUPS_BUTTON          1039
#define IDC_BUTTON_set_passline         1039
#define IDC_PROGRESS                    1040
#define IDC_BUTTON_FF                   1040
#define IDC_BUTTON_OUT                  1040
#define IDC_PROGRESS_FORMAT             1040
#define IDC_EDIT_CONFIG_PATH            1040
#define IDC_DEL_GROUPS_BUTTON           1040
#define IDC_EDIT_BACKUP_PATH            1041
#define IDC_STATIC_TIP                  1041
#define IDC_BUTTON_FRAME                1041
#define IDC_ADD_FACE_BUTTON             1041
#define IDC_EDIT_FACE_BUTTON            1042
#define IDC_SLIDER_PLAYPOS              1043
#define IDC_DEL_FACE_BUTTON             1043
#define IDC_PLAYBACK_AREA               1044
#define IDC_GET_CH_SNAP_LIST_BUTTON     1044
#define IDC_STATIC_SPEED                1045
#define IDC_SEARCH_IMG_BY_IMG_BUTTON    1045
#define IDC_LIST_LOG                    1046
#define IDC_PLAYBACK_AREA2              1046
#define IDC_GET_ALARM_TRIGGER_BUTTON    1046
#define IDC_DATETIMEPICKER_START_TIME   1047
#define IDC_PLAYBACK_AREA3              1047
#define IDC_SET_ALARM_TRIGGER_BUTTON    1047
#define IDC_DATETIMEPICKER_END_TIME     1048
#define IDC_PLAYBACK_AREA4              1048
#define IDC_CHECK_LOG_SYSOP             1049
#define IDC_CHECK_LOG_CONFOP            1050
#define IDC_CHECK_LOG_PLAYBACK          1051
#define IDC_CHECK_LOG_BACKUP            1052
#define IDC_CHECK_LOG_SEARCH            1053
#define IDC_CHECK_LOG_VIEW_INFO         1054
#define IDC_CHECK_LOG_ERROR             1055
#define IDC_LIST2                       1057
#define IDC_LIST_DISKRECDATE            1057
#define IDC_BUTTON2                     1058
#define IDC_BUTTON_DISK_FORMAT          1058
#define IDC_BUTTON_CONFIG_PATH_BROWSE   1058
#define IDC_BUTTON_CAPTURE              1058
#define IDC_BUTTON_PLAYBACKSAVE         1058
#define IDC_COPY_FACE_BUTTON            1058
#define IDC_BUTTON_SAVETOUSB            1058
#define IDC_BUTTON_CHANGESYSTIME        1059
#define IDC_BUTTON_AUTO_SCAN            1059
#define IDC_BUTTON_Upgrade_PATH_BROWSE  1059
#define IDC_DATETIMEPICKER_SYSTIME      1060
#define IDC_BUTTON_TRACK_RECORD         1060
#define IDC_BUTTON_Upgrade              1060
#define IDC_SLIDER_VOICECOMM_VOLUME     1061
#define IDC_BUTTON_TRACK                1061
#define IDC_BUTTON_CONFIG_PATH_BROWSE2  1061
#define IDC_BUTTON_SENDXML              1061
#define IDC_BUTTON_VOICE_COMM           1062
#define IDC_BUTTON_LIVESAVE             1062
#define IDC_SLIDER_PTZ_SPEED            1063
#define IDC_BUTTON_GetSYSTIME           1064
#define IDC_BUTTON_CAPTURE2             1064
#define IDC_BUTTON_CAPTURE_JPEG         1064
#define IDC_BUTTON_AUTO_SCAN2           1065
#define IDC_COMBO_DATE_FORMAT           1070
#define IDC_COMBO_TIME_FORMAT           1071
#define IDC_COMBO_TIME_ZONE             1072
#define IDC_EDIT_NET_TIME_SERVER        1074
#define IDC_EDIT_EXPORT_PATH            1075
#define IDC_BUTTON_BROWSE_IMPORT_PATH   1076
#define IDC_EDIT_IMPORT_PATH            1077
#define IDC_BUTTON_IMPORT               1078
#define IDC_BUTTON_ENTER_EXIT_CONFIG    1079
#define IDC_BUTTON_SAVE_LIVE            1080
#define IDC_Btn_GetDevice               1080
#define IDC_Btn_SetDeviceName           1081
#define IDC_BUTTON_SAVE_TIME            1082
#define IDC_Btn_GetDeviceIPCamInfo      1082
#define IDC_CHECK_SYNC_TIME             1083
#define IDC_BUTTON_SMART_SBSCRIB_AVD    1083
#define IDC_Btn_GetDeviceInfo           1083
#define IDC_LIST_LIVE                   1084
#define IDC_BUTTON_SMART_SBSCRIB_VFD    1084
#define IDC_BUTTON_EXPORT               1085
#define IDC_BUTTON_SMART_SBSCRIB_       1085
#define IDC_BUTTON_SMART_SBSCRIB_VFD_MATCH 1085
#define IDC_BUTTON_SMART_SBSCRIB_AVD2   1085
#define IDC_BUTTON_LIVE_DEFAULT         1086
#define IDC_BUTTON_TIME_DEFAULT         1087
#define IDC_BUTTON_IRIS                 1088
#define IDC_COMBO_PRESET                1089
#define IDC_BUTTON_PRESET_SET           1090
#define IDC_BUTTON_PRESET_GO            1091
#define IDC_BUTTON_PRESET_DEL           1092
#define IDC_COMBO_CRUISE                1093
#define IDC_BUTTON_CRUISE_SETUP         1094
#define IDC_BUTTON_CRUISE               1096
#define IDC_COMBO_FISHEYEMODE           1097
#define IDC_CUSTOM_CRUISE               1099
#define IDC_STATIC_HEHE                 1100
#define IDC_BUTTON_CHANGE_DISK_PROPERTY 1101
#define IDC_CUSTOM_DISK_LIST            1102
#define IDC_BUTTON_DISK_REFRESH         1103
#define IDC_COMBO_CONFIG_CHNN           1104
#define IDC_CHECK_CONFIG_SYSBASIC       1106
#define IDC_CHECK_CONFIG_DATETIME       1107
#define IDC_CHECK_CONFIG_DST            1108
#define IDC_CHECK_CONFIG_LIVE           1109
#define IDC_CHECK_CONFIG_MAINMONITOR    1110
#define IDC_CHECK_CONFIG_SPOT           1111
#define IDC_CHECK_CONFIG_AUDIO          1112
#define IDC_CHECK_CONFIG_CHNN           1113
#define IDC_CHECK_CONFIG_OSD            1114
#define IDC_CHECK_CONIFG_ENCODE         1115
#define IDC_CHECK_CONFIG_ENCODE_ALARM   1116
#define IDC_CHECK_CONFIG_ENCODE_NET     1117
#define IDC_CHECK_CONFIG_RECORD_PLAN    1118
#define IDC_CHECK_CONFIG_MOTION_PLAN    1119
#define IDC_CHECK_CONFIG_SENSOR_PLAN    1120
#define IDC_CHECK_CONFIG_NETWORK        1121
#define IDC_CHECK_CONFIG_NETWORK_DDNS   1122
#define IDC_CHECK_CONFIG_NETWORK_MAIL   1123
#define IDC_CHECK_COFNIG_USER           1124
#define IDC_CHECK_CONFIG_SENSOR         1125
#define IDC_CHECK_CONFIG_MOITON         1126
#define IDC_CHECK_CONFIG_VLOSS          1127
#define IDC_CHECK_CONFIG_PTZ            1128
#define IDC_CHECK_CONFIG_RECORD         1129
#define IDC_CHECK_CONFIG_COLOR          1130
#define IDC_BUTTON_SELECT_ALL           1131
#define IDC_BUTTON_CONFIG_GET           1132
#define IDC_BUTTON_MSG_CALLBACK         1133
#define IDC_BUTTON_CONFIG_SAVE          1134
#define IDC_LIST_MSG                    1135
#define IDC_RADIO_LOGIN                 1135
#define IDC_BUTTON_CONFIG_DEFAULT       1136
#define IDC_RADIO_AUTO                  1136
#define IDC_BUTTON3                     1137
#define IDC_RECORD                      1137
#define IDC_EDIT1                       1137
#define IDC_EDIT_DOMAIN                 1137
#define IDC_BUTTONM                     1137
#define IDC_BUTTON_Manual_Aram          1137
#define IDC_EDIT_DeviceName             1137
#define IDC_BtnReboot                   1137
#define IDC_EDIT_GROUP                  1137
#define IDC_BUTTON_GET_SAVEUSB_PROCESS  1137
#define IDC_EDIT_WATERMASK_INFO         1137
#define IDC_EDIT_WATERMASKINFO          1137
#define IDC_BUTTON_TALKT_RANS           1138
#define IDC_STC_PORT                    1138
#define IDC_EDIT_FACE_NAME              1138
#define IDC_EDIT_high_temperature       1138
#define IDC_BUTTON_GET_SAVEUSB_PROCESS2 1138
#define IDC_BUTTON_GETDISK_RECDATE      1138
#define IDC_BUTTON_ShowRect             1138
#define IDC_BUTTON_SELECT_REVERSE       1139
#define IDC_EDIT_FACE_birthday          1139
#define IDC_EDIT_low_temperature        1139
#define IDC_EDIT_FACE_nativePlace       1140
#define IDC_LIST_DEVICE                 1141
#define IDC_CHECK1                      1141
#define IDC_EDIT_FACE_certificateNum    1141
#define IDC_CHECK_LOG                   1141
#define IDC_BUTTON_DrawRect             1142
#define IDC_BUTTON_LogTest              1142
#define IDC_EDIT_FACE_mobile            1142
#define IDC_COMBO1                      1143
#define IDC_COMBO_Playback_Channels     1143
#define IDC_CMB_DEVICE                  1143
#define IDC_EDIT_FACE_number            1143
#define IDC_COMBO_FILETYPE              1143
#define IDC_COMBO_LOG_LEVEL             1143
#define IDC_COMBO_WATERSETCHL           1143
#define IDC_COMBO_NVREVENTCOMBO         1143
#define IDC_COMBO_StreamType            1144
#define IDC_COMBO_WATERMASKON           1144
#define IDC_EDIT_UpgradeFilePath        1146
#define IDC_BtnBankReplay               1149
#define IDC_SLIDER1                     1150
#define IDC_LIVE_DIVIDE_1               1151
#define IDC_LIVE_DIVIDE_2               1152
#define IDC_BtnBankSound2               1152
#define IDC_BtnBankFullScreen           1152
#define IDC_LIVE_DIVIDE_3               1153
#define IDC_LIVE_DIVIDE_4               1154
#define IDC_LIVE_DIVIDE_5               1155
#define IDC_LIVE_DIVIDE_6               1156
#define IDC_LIVE_DIVIDE_7               1157
#define IDC_LIVE_DIVIDE_8               1158
#define IDC_LIVE_DIVIDE_9               1159
#define IDC_STATIC_DevSN                1159
#define IDC_LIVE_DIVIDE_10              1160
#define IDC_LIVE_DIVIDE_11              1161
#define IDC_LIVE_DIVIDE_12              1162
#define IDC_LIVE_DIVIDE_13              1163
#define IDC_LIVE_DIVIDE_14              1164
#define IDC_LIVE_DIVIDE_15              1165
#define IDC_LIVE_DIVIDE_16              1166
#define IDC_BTN_PTZ_3D_CTRL             1167
#define IDC_BTN_MAKEIFRAME_MAIN         1168
#define IDC_BTN_MAKEIFRAME              1168
#define IDC_BUTTON4                     1169
#define IDC_BUTTON_TRANSPARENT          1169
#define IDC_BUTTON_SMART_SBSCRIB_OSC    1169
#define IDC_BTN_EXPORT                  1169
#define IDC_BUTTON_ACTIVEDEV            1169
#define IDC_STATIC_GROUPS               1170
#define IDC_STATIC_FACE                 1171
#define IDC_STATIC_GROUPS3              1171
#define IDC_LIST_GROUPS                 1172
#define IDC_STATIC_GROUPS4              1172
#define IDC_LIST_FACE                   1173
#define IDC_STATIC_GROUPS5              1173
#define IDC_STATIC_GROUPS2              1174
#define IDC_LIST_CH_SNAP                1175
#define IDC_CH_COMBO                    1176
#define IDC_STATIC_text                 1177
#define IDC_EDIT_URL                    1178
#define IDC_EDIT_SENDURL                1178
#define IDC_LIST_SEARCH_IMAGE_RESULT    1178
#define IDC_LIST_CH_SNAP2               1178
#define IDC_EDIT_URL2                   1179
#define IDC_EDIT_SENDXML                1179
#define IDC_RADIO_MAIN                  1179
#define IDC_EDIT_XML                    1180
#define IDC_EDIT_RSCVXML                1180
#define IDC_EDIT_RECVXML                1180
#define IDC_RADIO_SUB                   1180
#define IDC_BUTTON_UpgradeIPC           1181
#define IDC_STATIC_PROCESS              1182
#define IDC_BTN_EXPORT_BROWSE           1184
#define IDC_PROGRESS_EXPORT             1185
#define IDC_BTN_IMPORT                  1186
#define IDC_STATIC_TOTAL                1187
#define IDC_PICTURE                     1188
#define IDC_STATIC_PICTURE_PATH         1189
#define IDC_BUTTON5                     1190
#define IDC_BUTTON_SMART_SBSCRIB_PEA    1190
#define IDC_GET_CH_SNAP_LIST_V2_BUTTON  1190
#define IDC_BTN_ADDUSER                 1190
#define IDC_RADIO2                      1192
#define IDC_RADIO_BY_ALLOWLIST          1192
#define IDC_BUTTON7                     1196
#define IDC_BUTTON_SMART_SBSCRIB_AOIENTRY 1196
#define IDC_BUTTON_SMART_AOIENTRY       1196
#define IDC_BUTTON6                     1197
#define IDC_BUTTON_SMART_SBSCRIB_VIHICLE 1197
#define IDC_SEARCH_IMG_BY_IMG_V2_BUTTON 1197
#define IDC_EDIT2                       1198
#define IDC_BUTTON_SMART_SBSCRIB_PASSLINE 1198
#define IDC_EDIT_ACTIVEPWD              1198
#define IDC_BUTTON_SMART_SBSCRIB_VIHICLE2222 1199
#define IDC_BUTTON_SMART_SBSCRIB_AOILEAVE 1199
#define IDC_BUTTON_SMART_AOIENTRY1      1200
#define IDC_BUTTON_SMART_AOILEAVE       1200
#define IDC_BUTTON_SUBSCRIBE_NVRPASSLINE 1200
#define IDC_BUTTON_SMART_SBSCRIB_PASSLINE2 1200
#define IDC_GET_CH_SNAP_LIST_V3_BUTTON  1201
#define IDC_BUTTON_UNSUBSCRIBE_SMARTSTREAM 1201
#define IDC_BUTTON_UNSUBSCRIBE_NVRPASSLINE 1201
#define IDC_BUTTON_SMART_SBSCRIB_PASSLINE3 1201
#define IDC_SEARCH_IMG_BY_IMG_V3_BUTTON 1202
#define IDC_BUTTON_SMART_SBSCRIB_TRAFFIC 1202
#define IDC_PICTURE_SNAP                1203
#define IDC_LIST_IMAGE                  1204
#define IDC_RADIO_BY_ALL                1205
#define IDC_RADIO_BY_STRAGER            1206
#define IDC_RADIO_BY_BLOCKLIST          1207
#define IDC_RADIO5                      1208
#define IDC_RADIO6                      1209
#define IDC_RADIO7                      1210
#define IDC_DATETIMEPICKER1             1211
#define IDC_CHECK2                      1212
#define IDC_CHECK3                      1213
#define IDC_CHECK4                      1214
#define IDC_CHECK5                      1215
#define IDC_CHECK6                      1216
#define IDC_RADIO_IMG_FROM_ALBUM        1217
#define IDC_RADIO_IMG_FROM_SNAP         1218
#define IDC_RADIO_IMG_FROM_GROUP        1219
#define IDC_RADIO_IMG_FROM_EXTERNAL     1220
#define IDC_PICTURE_SNAP2               1221
#define IDC_RADIO_SNAP                  1222
#define IDC_RADIO11                     1223
#define IDC_RADIO_ORIGINAL              1223
#define IDC_CHECK_enable                1232
#define IDC_COMBO_unit                  1233
#define IDC_COMBO_alarmtime             1234
#define IDC_CHECK_voice                 1235
#define IDC_CHECK_capture               1236
#define IDC_CHECK_recode                1237
#define IDC_BUTTON_get_temperature      1238
#define IDC_CHECK_mask_enable           1239
#define IDC_COMBO_mask_alarmtime        1240
#define IDC_CHECK_mask_voice            1241
#define IDC_CHECK_mask_capture          1242
#define IDC_CHECK_mask_recode           1243
#define IDC_BUTTON_get_mask             1244
#define IDC_EDIT_msg                    1245
#define IDC_CHECK_high_temperature      1246
#define IDC_CHECK_low_temperature       1247
#define IDC_STATIC_high                 1248
#define IDC_STATIC_low                  1249
#define IDC_EDIT_msg_vfd                1250
#define IDC_BUTTON8                     1250
#define IDC_BUTTON_SEARCH_DEVICE        1250
#define IDC_CHECK_thermal_enable        1251
#define IDC_BUTTON_SET_LOG              1251
#define IDC_BUTTON_get_thermal          1252
#define IDC_EDIT_LOGPATH                1252
#define IDC_CHECK_passline_enable       1253
#define IDC_BUTTON9                     1253
#define IDC_BUTTON_BROWSE_LOGPATH       1253
#define IDC_BUTTON_get_passline         1254
#define IDC_BUTTON_SEARCH_ACTIVEDEV     1254
#define IDC_EDIT_msg_passline           1255
#define IDC_BUTTON_passline_reset       1256
#define IDC_SNAP_PICTURE                1256
#define IDC_BUTTON_get_passline2        1257
#define IDC_BUTTON_get_passline_count   1257
#define IDC_TARGET_PICUTRE              1257
#define IDC_SOURCE_PICUTRE              1258
#define IDC_STATIC_TIME                 1259
#define IDC_STATIC_SIMILARITY           1260
#define IDC_STATIC_NAME                 1261
#define IDC_STATIC_CREDENTIAL           1262
#define IDC_RADIO_IP                    1263
#define IDC_RADIO_DOMAIN                1264
#define IDC_RADIO_NAT                   1265
#define IDC_RADIO_NAT2                  1266
#define IDC_STATIC_DISKRECDATE          1268
#define IDC_STATIC_WATERMARK            1269
#define IDC_LIST_SEARCHDEVICE           1270
#define IDC_STATIC_TIPS                 1272
#define IDC_CHECK_TALK_TO_CHANNEL       1273
#define ID_LIVE_AUDIO                   32771
#define ID_LIVE_CAPTURE                 32772
#define ID_PLAYBACKSPEED_1_32x          32773
#define ID_PLAYBACKSPEED_1_16x          32774
#define ID_PLAYBACKSPEED_1_8x           32775
#define ID_PLAYBACKSPEED_1_4x           32776
#define ID_PLAYBACKSPEED_1_2x           32777
#define ID_PLAYBACKSPEED_1X             32778
#define ID_PLAYBACKSPEED_2X             32779
#define ID_PLAYBACKSPEED_4X             32780
#define ID_PLAYBACKSPEED_8X             32781
#define ID_PLAYBACKSPEED_16X            32782
#define ID_PLAYBACKSPEED_32X            32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1274
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
